language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - build-tools-21.1.2
    - android-21
    - extra-android-m2repository
    # Uncomment this if you need emulator
    # - sys-img-x86-android-21
  licenses:
    - 'android-sdk-license-.+'

before_install:
    - export TERM=dumb
    - chmod +x gradlew

# Uncomment this if you need emulator
# before_script:
#  - echo no | android create avd --force -n test -t android-21 --abi x86
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &

# Robolectric tests
script:
    - ./gradlew build check

# Instrument tests
# script: ./gradlew build check connectedCheck

branches:
  only:
    - master
    - production

# after_success: uncomment this and add your own deployment targets